services:
  - type: web
    name: learning-tracker
    plan: free
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kunnikarboon_db_user:26gmSoa6PntP6tMF@cluster0.eljpkau.mongodb.net/learning-tracker?retryWrites=true&w=majority 
      - key: PORT
        value: 5500
