services:
  - type: web
    name: learning-tracker-backend
    plan: free
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
      - key: PORT
        value: 5500
